version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_AUTH_PLUGIN: 'mysql_native_password'
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    network_mode: host